_name_or_path:
    value: distilbert-base-uncased
_wandb:
    value:
        cli_version: 0.26.1
        e:
            zo1j8idz3iq33vp69e7svh146rdvhczc:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    macModel: Mac16,12
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "2415919104"
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "483676352512"
                email: clc2240@columbia.edu
                executable: /Users/ccahill/Desktop/HPML/AssetOpsBench/.venv/bin/python3
                git:
                    commit: 49b0cb071de7bd218aa97af92abdbde1da4e5319
                    remote: https://github.com/jasonlee-1024/AssetOpsBench.git
                host: Mac.lan
                memory:
                    total: "25769803776"
                os: macOS-15.7.4-arm64-arm-64bit
                program: -m src.llm.lmtrain
                python: CPython 3.12.11
                root: /Users/ccahill/Desktop/HPML/AssetOpsBench
                startedAt: "2026-05-07T15:20:21.814281Z"
                writerId: zo1j8idz3iq33vp69e7svh146rdvhczc
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.11
        t:
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
            "3":
                - 7
                - 13
                - 16
                - 19
                - 62
                - 66
            "4": 3.12.11
            "5": 0.26.1
            "9":
                "1": transformers_trainer
            "12": 0.26.1
            "13": darwin-arm64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation:
    value: gelu
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
architectures:
    value:
        - DistilBertForMaskedLM
attention_dropout:
    value: 0.1
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
batch_eval_metrics:
    value: false
batch_size:
    value: 16
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset:
    value: AssestOpsBench
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_static_graph:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: null
dim:
    value: 768
disable_tqdm:
    value: false
do_eval:
    value: true
do_predict:
    value: false
do_train:
    value: false
dropout:
    value: 0.1
dtype:
    value: float32
enable_jit_checkpoint:
    value: false
eos_token_id:
    value: null
epochs:
    value: 3
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: epoch
eval_use_gather_object:
    value: false
fp16:
    value: false
fp16_full_eval:
    value: false
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
hidden_dim:
    value: 3072
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_num_input_tokens_seen:
    value: "no"
initializer_range:
    value: 0.02
is_encoder_decoder:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 2e-05
length_column_name:
    value: length
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: null
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 20
logging_strategy:
    value: steps
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_position_embeddings:
    value: 512
max_steps:
    value: -1
metric_for_best_model:
    value: null
model/num_parameters:
    value: 66955010
model_name:
    value: distilbert-base-uncased
model_type:
    value: distilbert
n_heads:
    value: 12
n_layers:
    value: 6
neftune_noise_alpha:
    value: null
num_train_epochs:
    value: 3
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: models/lmtrain
output_hidden_states:
    value: false
pad_token_id:
    value: 0
parallelism_config:
    value: null
per_device_eval_batch_size:
    value: 16
per_device_train_batch_size:
    value: 16
prediction_loss_only:
    value: false
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
qa_dropout:
    value: 0.1
remove_unused_columns:
    value: true
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
run_name:
    value: classifier_distilbert-base-uncased
save_on_each_node:
    value: false
save_only_model:
    value: false
save_steps:
    value: 500
save_strategy:
    value: epoch
save_total_limit:
    value: null
seed:
    value: 42
seq_classif_dropout:
    value: 0.2
sinusoidal_pos_embds:
    value: false
skip_memory_metrics:
    value: true
tf32:
    value: null
threshold:
    value: 0.5
tie_weights_:
    value: true
tie_word_embeddings:
    value: true
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
trackio_bucket_id:
    value: null
trackio_space_id:
    value: null
trackio_static_space_id:
    value: null
train_sampling_strategy:
    value: random
transformers_version:
    value: 5.8.0
use_cache:
    value: false
use_cpu:
    value: false
use_liger_kernel:
    value: false
vocab_size:
    value: 30522
warmup_ratio:
    value: null
warmup_steps:
    value: 0
weight_decay:
    value: 0
