_wandb:
    value:
        cli_version: 0.26.1
        e:
            f63eatziowltybi00o7h4wyyb3m84z4g:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    macModel: Mac16,12
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "2415919104"
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "483339735040"
                email: clc2240@columbia.edu
                executable: /Users/ccahill/Desktop/HPML/AssetOpsBench/.venv/bin/python3
                git:
                    commit: 49b0cb071de7bd218aa97af92abdbde1da4e5319
                    remote: https://github.com/jasonlee-1024/AssetOpsBench.git
                host: Mac.lan
                memory:
                    total: "25769803776"
                os: macOS-15.7.4-arm64-arm-64bit
                program: -m src.llm.lmtrain
                python: CPython 3.12.11
                root: /Users/ccahill/Desktop/HPML/AssetOpsBench
                startedAt: "2026-05-07T15:12:43.175547Z"
                writerId: f63eatziowltybi00o7h4wyyb3m84z4g
        m: []
        python_version: 3.12.11
        t:
            "2":
                - 49
                - 51
            "3":
                - 13
                - 16
            "4": 3.12.11
            "5": 0.26.1
            "12": 0.26.1
            "13": darwin-arm64
batch_size:
    value: 16
dataset:
    value: AssestOpsBench
epochs:
    value: 3
learning_rate:
    value: 2e-05
model_name:
    value: distilbert-base-uncased
threshold:
    value: 0.5
